# Generated by Django 6.0 on 2026-01-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[('draft', 'draft'), ('published', 'published')], default=0),
        ),
    ]
