# Generated by Django 6.0 on 2026-01-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=20),
        ),
    ]
